# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/haoyu/ppr/BDPush

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/haoyu/ppr/BDPush

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/haoyu/ppr/BDPush/CMakeFiles /home/haoyu/ppr/BDPush//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/haoyu/ppr/BDPush/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graph

# Build rule for target.
graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graph
.PHONY : graph

# fast build rule for target.
graph/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/build
.PHONY : graph/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named algo

# Build rule for target.
algo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 algo
.PHONY : algo

# fast build rule for target.
algo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algo.dir/build.make CMakeFiles/algo.dir/build
.PHONY : algo/fast

#=============================================================================
# Target rules for targets named bppr

# Build rule for target.
bppr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bppr
.PHONY : bppr

# fast build rule for target.
bppr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bppr.dir/build.make CMakeFiles/bppr.dir/build
.PHONY : bppr/fast

src/algo.o: src/algo.cc.o
.PHONY : src/algo.o

# target to build an object file
src/algo.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algo.dir/build.make CMakeFiles/algo.dir/src/algo.cc.o
.PHONY : src/algo.cc.o

src/algo.i: src/algo.cc.i
.PHONY : src/algo.i

# target to preprocess a source file
src/algo.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algo.dir/build.make CMakeFiles/algo.dir/src/algo.cc.i
.PHONY : src/algo.cc.i

src/algo.s: src/algo.cc.s
.PHONY : src/algo.s

# target to generate assembly for a file
src/algo.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algo.dir/build.make CMakeFiles/algo.dir/src/algo.cc.s
.PHONY : src/algo.cc.s

src/bppr.o: src/bppr.cc.o
.PHONY : src/bppr.o

# target to build an object file
src/bppr.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bppr.dir/build.make CMakeFiles/bppr.dir/src/bppr.cc.o
.PHONY : src/bppr.cc.o

src/bppr.i: src/bppr.cc.i
.PHONY : src/bppr.i

# target to preprocess a source file
src/bppr.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bppr.dir/build.make CMakeFiles/bppr.dir/src/bppr.cc.i
.PHONY : src/bppr.cc.i

src/bppr.s: src/bppr.cc.s
.PHONY : src/bppr.s

# target to generate assembly for a file
src/bppr.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bppr.dir/build.make CMakeFiles/bppr.dir/src/bppr.cc.s
.PHONY : src/bppr.cc.s

src/graph.o: src/graph.cc.o
.PHONY : src/graph.o

# target to build an object file
src/graph.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/src/graph.cc.o
.PHONY : src/graph.cc.o

src/graph.i: src/graph.cc.i
.PHONY : src/graph.i

# target to preprocess a source file
src/graph.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/src/graph.cc.i
.PHONY : src/graph.cc.i

src/graph.s: src/graph.cc.s
.PHONY : src/graph.s

# target to generate assembly for a file
src/graph.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph.dir/build.make CMakeFiles/graph.dir/src/graph.cc.s
.PHONY : src/graph.cc.s

src/utils.o: src/utils.cc.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils.cc.o
.PHONY : src/utils.cc.o

src/utils.i: src/utils.cc.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils.cc.i
.PHONY : src/utils.cc.i

src/utils.s: src/utils.cc.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/utils.dir/build.make CMakeFiles/utils.dir/src/utils.cc.s
.PHONY : src/utils.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... algo"
	@echo "... bppr"
	@echo "... graph"
	@echo "... utils"
	@echo "... src/algo.o"
	@echo "... src/algo.i"
	@echo "... src/algo.s"
	@echo "... src/bppr.o"
	@echo "... src/bppr.i"
	@echo "... src/bppr.s"
	@echo "... src/graph.o"
	@echo "... src/graph.i"
	@echo "... src/graph.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

